### ISSUE TITLE
BySalesforce.label can't find a text nested in labelCol

### ISSUE THREAD

**Issue by jvervaec** [darcy-framework/darcy-salesforce#11]
Usually labelCol looks like this
`<td class="labelCol">Tier</td>`
but sometimes when there's a special hover help, it looks like this
`<td class="labelCol"><span class="helpButton" id="01I600000006eij.00Nm0000000Tb3o-_help">Is Primary<img src="/s.gif" alt="" class="helpOrb" title=""><script>...</script></span></td>`

Normally text() can find nested text, but it seems not in this case.

$x("//td[text()='Is Primary']")
`[]`
$x("//td/span[text()='Is Primary']")
`[<span class=​"helpButton" id=​"01I600000006eij.00Nm0000000Tb3o-_help">​"Is Primary"<img src=​"/​s.gif" alt class=​"helpOrb" title>​<script>​…​</script>​</span>​`

One potential fix is to use an OR in the xpath, but it's getting pretty gnarley.
`String xpath = "//div[@class='pbSubsection']//td[" + withClass("dataCol") + " and " +
                    "(preceding-sibling::td[1][" + withClass("labelCol") + " and text()='" + label + "'] "
                            + "| preceding-sibling::td[1][" + withClass("labelCol") + "]/span[text()='" + label + "'])]";`

**Comment by alechenninger** [comment]
Hrm, I think we talked about this once before, but let's meet up again and talk about this one

**Comment by alechenninger** [comment]
Based on our conversation, this might work:

`String xpath = "//div[@class='pbSubsection']//td[" + withClass("dataCol") + " and " +
                    "preceding-sibling::td[1][" + withClass("labelCol") + "]//*[text()='" + label + "'])]";`

**Comment by jvervaec** [comment]
I think I cracked it. Instead of //*[text()='blah'], do //text()='blah' and that works whether the text is nested or not.

String xpath = "//div[@class='pbSubsection']//td[" + withClass("dataCol") + 
                    " and " + "preceding-sibling::td[1][" + withClass("labelCol") + 
                    "]//text()='" + label + "']";

This also seems to work for the Edit page, so we don't really need to do a separate BySalesforceEditLabel locator anymore.  This gets you the td in either case and then you still by chained down to the html element.  

Then we can fix withClass() to do something like [contains(@class,'data' and 
contains(@class,'col')] to fix the issue with the Visualforce (apex) pages where the classes are label2col, data3col, etc.

Need to test it out some more still.

**Comment by alechenninger** [comment]
Let's ignore apex for now, I'll create a separate issue. Now that that code is generic enough, we can make some additional locator factory methods on `BySalesforce` like `BySalesforce.inputLabel` and `BySalesforce.textLabel` and `BySalesforce.selectLabel`, etc.

**Comment by alechenninger** [comment]
I lost track of where we are on this. Has this been fixed already?

**Comment by jvervaec** [comment]
Yep. It was in #13
