### ISSUE TITLE
BySalesforce.label doesn't recognize 'multiclass' td

### ISSUE THREAD

**Issue by jvervaec** [darcy-framework/darcy-salesforce#9]
Given the markup `<td class="last labelCol">Some Label</td>`

We interpreted that as a td with 2 classes, `class="last" and class="labelCol", but xpath (or maybe webdriver doesn't seem to agree.

The xpath expression in BySalesforce.label `...preceding-sibling::td[1][@class='labelCol' and text()='Some Label']]...` won't find the above markup.  Changing `@class='labelCol'` to `contains(@class,'labelCol')` seems to fix the issue.  I don't think there are any cases where one might inadvertently find some other class partially called labelCol inside a pbSubsection.

I can submit a pull request for this change.

**Comment by alechenninger** [comment]
Will be fixed in #10

**Comment by alechenninger** [comment]
Fixed with #10
